services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./identity-postgres:/var/lib/postgresql/data
  rinkudesu-identity:
    image: ghcr.io/rinkudesu/rinkudesu-identity:latest
    restart: unless-stopped
    build:
      context: ..
      dockerfile: Rinkudesu.Identity.Service/Dockerfile
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:80:80"
    environment:
      RINKU_IDENTITY_CONNECTIONSTRING: "Server=postgres;Port=5432;Database=rinku-links;User Id=postgres;Password=postgres;"
      RINKU_IDENTITY_BASEURL: http://rinkudesu-links/
      RINKU_IDENTITY_REDIS: redis:6379
      RINKU_ARGON_SECRET: "replace with secure random string"
    command:
      - "--applyMigrations"
  redis:
    image: redis
    restart: unless-stopped
